### PR TITLE
AsciiDoc documentation

### PR DESCRIPTION
**Pull request by salaboy**
- Initial version of the AsciiDoc documentation. 
I will add more sections when this is merged, and we can incrementally improve it

### CODE REVIEW

**Comment by salaboy** [comment]
@spencergibb for some reason the build is failing but not in the docs..

**Comment by geoand** [comment]
@salaboy It's been failing since 2 days ago for some very weird reason that was unable to determine from the little check I did

**Comment by ryanjbaxter** [comment]
When I build your branch I get 
```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7:process-asciidoc (generate-docbook) on project spring-cloud-kubernetes-docs: Execution generate-docbook of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7:process-asciidoc failed: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /Users/ryanjbaxter/temp/spring-cloud-kubernetes/docs/src/main/asciidoc/spring-cloud-kubernetes.adoc
```

**Comment by salaboy** [comment]
@ryanjbaxter hmm interesting.. can you share which version of JDK and Maven are you using in your build? Also which maven goals is the pipeline executing?  I just built it (clean install) locally without any problems.

**Comment by salaboy** [comment]
@ryanjbaxter I will try to add a spring-cloud-kubernetes.adoc .. that might be a required root doc

**Comment by ryanjbaxter** [comment]
I am using the `mvnw` binary.  I am running `./mvnw clean install -Pdocs`

**Comment by ryanjbaxter** [comment]
I am unsure as to why the circleci build is failing, but it built fine locally for me.  However the generated docs only have one section `1. Why do you need Spring Cloud Kubernetes?`, there should be more right?

**Comment by salaboy** [comment]
@ryanjbaxter let me check that

**Comment by salaboy** [comment]
@ryanjbaxter docs fixed can you please recheck.. we need to find out what is going wrong in core.

**Pull request merged**
