### PR TITLE
Change getProperty method in order to set the target type

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Can you submit this against the 2.2.x branch and we can merge it forward?

**Comment by eddumelendez** [comment]
@ryanjbaxter done

**Comment by ryanjbaxter** [comment]
@eddumelendez the circleci build is broken due to unreleated issues, but when I run your code locally I am seeing test failures, do you not see them on your machine?

**Comment by eddumelendez** [comment]
@ryanjbaxter sorry for the delay. tests run ok locally.

**Comment by ryanjbaxter** [comment]
Looks like you might need to update your branch to pull in the latest changes

**Comment by eddumelendez** [comment]
done

**Pull request merged**
