### PR TITLE
Fix misprint in README.adoc ("Oeriodically").

### PR DESCRIPTION
**Pull request by saltos**

### CODE REVIEW

**Comment by saltos** [comment]
I just wonder why this change failed some checkstyle validation in Java code...

**Comment by geoand** [comment]
@ryanjbaxter any idea?

**Comment by pukkaone** [comment]
Commit https://github.com/spring-cloud/spring-cloud-kubernetes/commit/a9b1229a707ff675e398d80d0fbe23da70aba453 replaced `http://www.apache.org/licenses/LICENSE-2.0` with `https://www.apache.org/licenses/LICENSE-2.0` in the header comments, but Checkstyle wants the former.

**Comment by saltos** [comment]
Have you any idea how to fix this build?

**Pull request merged**
