### PR TITLE
update kubernetes-client to 5.5.0

### PR DESCRIPTION
**Pull request by balihb**
upgrade kubernetes-client for bringing in watcher changes.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
thanks for this.  Can you fix the checkstyle errors?

**Comment by balihb** [comment]
done

**Comment by balihb** [comment]
can we backport it to 2.0.x or some branch that will have a release soon?

**Comment by ryanjbaxter** [comment]
Amazing, thanks for this!

I am kind of surprised there were no breaking changes updating the Kuberentes Java client 🤔

We cannot make this change in the 2.0.x branch because of the potential downstream effects on applications, we could break them, and we can't do that in a minor release.

**Comment by balihb** [comment]
everything should be ok now.

I will try this change on a real application today. we can wait for that with the merge if we want to.

**Comment by balihb** [comment]
failure is an external dependency failure during docker image build.

**Comment by balihb** [comment]
the test with the app was a success. the ci could be rerun, but I have no rights for it. other than that this should be ready for merge.

**Comment by wind57** [comment]
what a lovely PR, as an addendum you can subscribe to the releases that fabric8 pushes and keep updating when that happens, if you want. 

and btw you can always do a `git commit --allow-empty -m 'retrigger build'`, so that the build starts again.

**Comment by balihb** [comment]
nice to know!

**Pull request merged**
