### PR TITLE
fix 825

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Review by ryanjbaxter — APPROVED** [review]
I reran the build, this looks good to me.

**Comment by wind57** [comment]
thank you - then it is ready.

**Review by ryanjbaxter — CHANGES_REQUESTED** [review]
Actually we should make the same changes for the Kubernetes Client indicators as well.

**Comment by wind57** [comment]
the PR is [out for that already](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/830)

**Comment by ryanjbaxter** [comment]
Sorry I missed, that thanks!

**Pull request merged**
