### PR TITLE
unique service names (2.1.x)

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Comment by wind57** [comment]
I can't understand why the PR checks are not triggered here :| will try again later in the day

**Comment by ryanjbaxter** [comment]
I dont think we ever added github actions to the 2.1.x branch

**Comment by wind57** [comment]
Ha! Indeed! :) You OK me creating a PR to add it?

**Comment by ryanjbaxter** [comment]
Looks like `ActuatorRefreshRabbitMQIT.testRefresh` is failing.  Wouldnt think it would be related, but maybe.  Let me know if you have a chance to look at it.

**Comment by wind57** [comment]
oh wow, I totally forgot that `2.1.x` is still on kind, is it still worth to create a github actions pipeline? it might take a while from my side

Looking into the test locally to see what is going on...

**Comment by ryanjbaxter** [comment]
Actually it appears to be a fluke because the build passed this morning

**Comment by wind57** [comment]
1) so still OK for me to create a pipeline where tests run without integration tests? 
2) indeed the tests run just fine for me locally too - just tested it.

**Comment by ryanjbaxter** [comment]
>so still OK for me to create a pipeline where tests run without integration tests for 2.1.x?
yup!

**Pull request merged**
