### PR TITLE
fix ok http client explicit dependency

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Comment by wind57** [comment]
The changes are small, but it will take a significant amount of words explaining it, so please bear with me.

We need to first read carefully [this part of maven documentation](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#importing-dependencies) (the second example with Project `X`, `Y` and `Z` and what `a` dependency ends up being resolved). After we transpose that example to our code base (removed all irrelevant parts), we have this in `spring-cloud-kubernetes-dependencies`:


```
....
<dependencyManagement>
    <dependencies>
        ....
        <dependency>
		<groupId>io.kubernetes</groupId>
		<artifactId>client-java</artifactId>
		<version>${kubernetes-java-client.version}</version>
	</dependency>

         .....

        <dependency>
		<groupId>com.squareup.okhttp3</groupId>
		<artifactId>okhttp</artifactId>
		<version>${okhttp.version}</version>
	</dependency>
	<dependency>
		<groupId>com.squareup.okhttp3</groupId>
		<artifactId>logging-interceptor</artifactId>
		<version>${okhttp.version}</version>
	</dependency>

         .....

```

So `io.kubernetes:client-java:11.0.2` will have a transitive dependency : `com.squareup.okhttp3:okhttp:3.14.9` (https://repo1.maven.org/maven2/io/kubernetes/client-java-parent/11.0.2/client-java-parent-11.0.2.pom); but we try to bring an explicit one with version: `3.14.4`. (I am showing against `2.0.x` branch btw, but things have the same relevance in `main` too). 

Because the order in which these dependencies are written matters (that maven documentation might not be super explicit about it), it means that currently the explicit version that we try to use, is simply ignored. This means we can drop it. 

The downside is that if k8s-client ever drops okhttp client, some of our tests will fail, because the only place where we use okhttp is in tests or examples:

```
cd spring-cloud-kubernetes
 grep -r "com.squareup.okhttp3" --exclude .flattened-pom.xml . | sort --unique  
./spring-cloud-kubernetes-examples/kubernetes-loadbalancer-example/greeting-service/pom.xml:                    <groupId>com.squareup.okhttp3</groupId>
./spring-cloud-kubernetes-integration-tests/discovery/tests/pom.xml:                    <groupId>com.squareup.okhttp3</groupId>
./spring-cloud-kubernetes-integration-tests/pom.xml:                            <groupId>com.squareup.okhttp3</groupId>
./spring-cloud-kubernetes-integration-tests/simple-configmap/pom.xml:                   <groupId>com.squareup.okhttp3</groupId>
./spring-cloud-kubernetes-integration-tests/simple-core/pom.xml:                        <groupId>com.squareup.okhttp3</groupId>
```

**Comment by wind57** [comment]
@ryanjbaxter leaving a note here also - as this is ready for review too. It should address [this](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/846)

**Comment by ryanjbaxter** [comment]
Thanks for the detailed explaination!

So the reason why everything (the tests and examples) still compiles is because of the transitive dependency from `kubernetes-client`?

**Comment by wind57** [comment]
sort of. currently, even if `kubernetes-client` still drops ok http, our code will still compile and work, but only because we have that dependency in `dependencyManagement` and require it explicitly in those projects.

At the same time, if we drop it, it will _still_ work (as this PR proves), _because_ of the transitive dependency. The problem is that we override that transitive dependency version. To try and simplify this : `dependencyManagement` will tell what version of transitive dependency to use. 

So, if we drop it like in this PR : we rely on the transitive one.
At the same time, if we do not want to rely on that transitive one, we should not manage ok-http via bom; because in that case it simply overrides the dependency version that kubernetes client really requires. It's like a vicious circle.

**Comment by ryanjbaxter** [comment]
Right I agree.  I think its fine to drop the explicit dependency in the BOM and rely on `kubernetes-client`.  If they do drop it we can address what approach to take if/when that happens.

**Comment by wind57** [comment]
in that case, this is ready to be merged and the defect that this triggered, also. thank you or looking into this.

**Pull request merged**
