### PR TITLE
Add support for ExternalName service type

### PR DESCRIPTION
**Pull request by ArtyomGabeev**
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/489

### CODE REVIEW

**Comment by ArtyomGabeev** [comment]
Having a service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.service.example.com
```
We should be able to resolve service call http://my-service/doCall into http://my.service.example.com/doCall

Notes:
Because there is not information about secure/port, I left them false/0.

So it's up to client to specify schema http vs https, e.g: 
http**s**://my-service/doCall should become http**s**://my.service.example.com/doCall

Regrading port, I've checked LB Utils and ports will be 80/443.

**Comment by digows** [comment]
I've achieved that by changing the KubernetesServicesServerList.

`@Override
	public List<Server> getUpdatedListOfServers()
	{
		final List<Server> result = new ArrayList<>();

		final Service service = StringUtils.isNotBlank(this.namespace) ?
				this.client.services().inNamespace(this.namespace).withName(this.serviceId).get() :
				this.client.services().withName(this.serviceId).get();

		if ( service != null )
		{
			if ( LOG.isDebugEnabled() )
			{
				LOG.debug("Found Service[" + service.getMetadata().getName() + "]");
			}

			final String host;
			//is it a external service?
			if ( service.getSpec().getExternalName() != null )
			{
				host = service.getSpec().getExternalName();
			}
			//else, it will use the internal domain
			else
			{
				host = this.concatServiceFQDN(service);
			}

			if ( service.getSpec().getPorts().isEmpty() )
			{
				result.add(new Server(host, 80));
			}
			else if ( service.getSpec().getPorts().size() == 1 )
			{
				result.add(new Server(host, service.getSpec().getPorts().get(0).getPort()));
			}
			else
			{
				for ( ServicePort servicePort : service.getSpec().getPorts() )
				{
					if ( Utils.isNotNullOrEmpty(this.portName) || this.portName.endsWith(servicePort.getName()) )
					{
						result.add(new Server(host, servicePort.getPort()));
					}
				}
			}
		}

		if ( result.isEmpty() )
		{
			LOG.warn(String.format("Did not find any service in ribbon in namespace [%s] for name [%s] and portName [%s]", this.namespace, this.serviceId, this.portName));
		}
		return result;
	}`

**Comment by ArtyomGabeev** [comment]
KubernetesServicesServerList is used by Ribbon, which is in maintenance mode.

Proposed changes should work both for spring cloud load balancer as well.

**Comment by mindcrime** [comment]
Hey, just wondering if anybody could/would comment on if there is intention to merge this at some point? Just curious as we have a scenario where we really need ExternalName services to work with Ribbon as well.

**Comment by wind57** [comment]
this is my next thing to take care of, but for the initial phase, I'll add such support for the fabric8 client only (there are other features that will be ported to k8s client in the nearest future, this one included).

imo, such support for `ExternalName` services should be allowed only by opting into it via a property. The first reason is compatibility: we were not returning such services until now, so we should keep it that way; unless you want this explicitly. The second reason is that this will introduce more calls to the api-server, so having it optional is only reasonable to me.

Otherwise I will present a proposal PR in the upcoming days.

**Comment by wind57** [comment]
@ryanjbaxter this can be closed now. thank you.

**Pull request closed without merging**
