### PR TITLE
Refs #327 ~Fix property files searching in directories defined by

### PR DESCRIPTION
**Pull request by Lex4hex**
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/327 
Added recursive traversing of provided directory.

### CODE REVIEW

**Comment by geoand** [comment]
Looking at your PR, I guess I misunderstood what the problem was... Sorry about that!

The intention of a006296c was to remove the ability to traverse directories and locate properties files.
What I though the problem you described in #327 was that symlinks were not being used correctly.

So I am against this, sorry. If you want to add a PR that simply changes `.filter(Files::isRegularFile)` to something that doesn't filter out symlinks, I'd be happy to give +1

**Comment by Lex4hex** [comment]
@geoand The problem wasn't with filtering out symlinks. `.filter(Files::isRegularFile)` is actually working as it should. 
Paths property contains paths to directories with property files  e.g. `/config-volume`, right? 

``
this.properties.getPaths().stream().map(Paths::get)
``
That code returned only one path which is "/config-volume" and it's a directory so no property files are being imported from  `/config-volume`.

**Comment by geoand** [comment]
The whole idea of the discussion in #230 was to rationalize the way the ConfigMaps were turned into PropertySources. 
And part of that was to remove the traversing logic - since there is no analogy in a typical Spring Boot application. 
You now need to specify the entire path of the propertes/yaml file you wish to be included.

Do that make sense?

**Comment by Lex4hex** [comment]
Oh, I get it know, thanks. I thought you were talking only about traversing of nested directories. 
So, now I have to provide exact path to my mounted property files. 

Maybe it'll be good idea to directly point this out in docs?

**Comment by geoand** [comment]
> Oh, I get it know, thanks. I thought you were talking only about traversing of nested directories.
> So, now I have to provide exact path to my mounted property files.
> 

Yes that's the idea since that's exactly what Spring Boot does as well

> Maybe it'll be good idea to directly point this out in docs?

This is probably a good idea. Perhaps mentioning that the old behavior has been changed. Would you like to take that up? As I said before, I can obviously do that but it will take me a few days to get around to

**Comment by Lex4hex** [comment]
>This is probably a good idea. Perhaps mentioning that the old behavior has been changed. Would you like to take that up? As I said before, I can obviously do that but it will take me a few days to get around to 

Yep, I'll create a PR with update. 

I'm closing this PR then.

**Comment by geoand** [comment]
> > This is probably a good idea. Perhaps mentioning that the old behavior has been changed. Would you like to take that up? As I said before, I can obviously do that but it will take me a few days to get around to
> 
> Yep, I'll create a PR with update.
> 
> I'm closing this PR then.

Thanks for your help @Lex4hex and sorry for the misunderstanding on my part about the original issue

**Pull request closed without merging**
