### PR TITLE
Moving to use kubernetes-maven-plugin to support java 17

### PR DESCRIPTION
**Pull request by ryanjbaxter**

### CODE REVIEW

**Comment by wind57** [comment]
very interesting yet again. It seems that if you get this working, we should also close [this one](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/609/files).

**Comment by manusa** [comment]
Our current base image for JKube (1.5.2) is still based on Java 11. 

We'll soon release 1.6.0 with an updated base image Java 17 compatible. (https://github.com/eclipse/jkube/pull/1217)

For the current PR you can probably make it work by using the new base image --->
```xml
<properties>
  <!-- ... -->
  <jkube.generator.from>quay.io/jkube/jkube-java:0.0.13</jkube.generator.from>
</properties>
```

**Comment by manusa** [comment]
The enricher configuration(s) need updating, `<fmp-**>` tags should be replaced by `<jkube-**>`

**Comment by ryanjbaxter** [comment]
@manusa thanks for the pointers, I made those changes.

I am not entirely sure why I am getting this message or where it is coming from
`Did not find any kubernetes/openshift configuration files before starting the test execution. If you are using fabric8-maven-plugin, ensure `mvn package fabric8:resource fabric8:build` is run first to generate the resources.`

https://app.circleci.com/pipelines/github/spring-cloud/spring-cloud-kubernetes/1548/workflows/a1bf9f08-b334-41c4-b26c-6630268f47c0/jobs/2907/steps

Any insights would be appreciated.

**Comment by ryanjbaxter** [comment]
I made some progress, the problem at the moment is the deployment yaml generated by arquillian does not contain the registry in the image of the deployment so it fails to pull the image.  I need to think about this some more but I am leaning towards just moving these tests to use kind and not waste any more time here. Arqullian doesn't appear to be maintained anymore we need to move away from it anyways.

https://github.com/spring-cloud/spring-cloud-kubernetes/pull/923/files

**Comment by manusa** [comment]
Regarding the Docker issue, I think there might be some misconfiguration.

In the previous iteration you didn't need to push the image because the MicroK8s Docker daemon was shared with the host machine. The flag is different now (`jkube.docker.host`).

I'll try to check locally and create a PR to your branch.

**Comment by manusa** [comment]
With the changes in the following PR everything seems to work fine _(on my machine :shrug:)_

https://github.com/ryanjbaxter/spring-cloud-kubernetes/pull/1

**Comment by manusa** [comment]
:disappointed: these tests are really flaky. Is it possible to increase the CircleCI timeout?

**Comment by wind57** [comment]
That is why we started this work, cause we were hitting the limits of free tire on circleci. 

I am in the blur a little, Ive made a branch where some refactoring happened for these tests to Kind, but I guess the idea is to first stabilize the main branch with minimal changes, and then look at a different approach.

**Comment by ryanjbaxter** [comment]
@manusa i think there is a problem downloading the jacoco plugin on circleci at the moment

@wind57 if this does not get things working then we will scrap this effort and just rip the bandaid off, just trying to buy myself some time to look over those changes

**Comment by wind57** [comment]
Yay! It passed

**Pull request merged**
