### PR TITLE
Add labels to the health endpoint

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by spencergibb** [comment]
could you rebase to 2.2.x and retarget the PR?

**Comment by eddumelendez** [comment]
do you mean 1.1.x?

**Comment by spencergibb** [comment]
Yes

**Comment by eddumelendez** [comment]
@spencergibb target branch changed and the branch was also updated with `1.1.x`

**Comment by eddumelendez** [comment]
wondering if labels should be added to `KubernetesInfoContributor` too?

**Comment by eddumelendez** [comment]
tests run ok locally

**Pull request merged**
