### PR TITLE
Minor cleanup in dependencies

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Comment by wind57** [comment]
minor simplifications

**Comment by wind57** [comment]
@ryanjbaxter ready to be looked at. I started to look into fixing the issue with un-balanced tests and there are some things we need to do before that, so some PRs will be coming from me in that direction if you are OK. thank you

**Comment by wind57** [comment]
I feel bad for bothering you since you most probably are preparing for Barcelona spring.io. We might meet there, if I manager to steal a ticket from one of my co-workers :)

**Comment by ryanjbaxter** [comment]
Actually I am not going this year :(. So no worries!  Hope you get a ticket!

**Pull request merged**
