### PR TITLE
Remove redundant dependencies

### PR DESCRIPTION
**Pull request by weihubeats**
There are two `spring-boot-starter-logging dependencies` in `spring-cloud-kubernetes-commons`，We could remove one

### CODE REVIEW

**Comment by wind57** [comment]
shouldn't we drop the other one, that is `optional`? you are removing it from `commons`, so all project that use it should inherit it, while they in return should have it as `optional`. wdyt?

**Comment by weihubeats** [comment]
Now that I've removed the optional dependency, do I need to add
```xml
                <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
			<optional>true</optional>
		</dependency>
```
 to other projects that depend on the `spring-cloud-kubernetes-commons` module?

**Comment by wind57** [comment]
You will need to analyze each dependency individually and see if it makes sense. For example, `autoconfigure` dependency  depends on `commons` and is used in `config` and `discovery`... So it's not that trivial. For the time being, what you have here might be enough, as the purpose of this is to simply drop the duplicated dependency. Let's wait for the maintainers to see what they think.

**Comment by weihubeats** [comment]
ok

**Comment by wind57** [comment]
@ryanjbaxter can you glance over here? minor thing, but still worth it, imo. thank you

**Review by ryanjbaxter — APPROVED** [review]

**Pull request merged**
