### PR TITLE
rename *SpringBootTest to *IntegrationTests or just *Tests

### LINKED ISSUE #415: rename *SpringBootTest to *IntegrationTests or just *Tests
Make sure they are still picked up by default when running maven tests.

### PR DESCRIPTION
**Pull request by medmedchiheb**
cc @spencergibb  
first change, waiting for approval  

files changed::

`ConfigMapsFromFilePaths`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsFromFilePathsTests.java)

`ConfigMapsMixed`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master//spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsMixedTests.java)

`ConfigMaps`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsTests.java)

`ConfigMapsWithActiveProfilesName`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithActiveProfilesNameSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithActiveProfilesNameTests.java)

`ConfigMapsWithProfileExpression`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfileExpressionSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfileExpressionTests.java)

`ConfigMapsWithProfilesNoActiveProfile`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesNoActiveProfileSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesNoActiveProfileTests.java)

`ConfigMapsWithProfiles`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithProfilesTests.java)

`ConfigMapsWithoutProfiles`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithoutProfilesSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/ConfigMapsWithoutProfilesTests.java)

`MultipleConfigMaps`* : [original](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/MultipleConfigMapsSpringBootTest.java) | [updated](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/07d6a8c3c3b5f61bb8e52f7231adcc3460b0fb2c/spring-cloud-kubernetes-config/src/test/java/org/springframework/cloud/kubernetes/config/MultipleConfigMapsTests.java)

Fixes #415

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Thanks I think I would prefer that we just remove `SpringBoot` from the name, it seems unnecessary.  Also why the addition of `.checkstyle`?

**Comment by medmedchiheb** [comment]
@ryanjbaxter  so, shall i continue for other classes!

**Comment by ryanjbaxter** [comment]
Yes please!

**Comment by medmedchiheb** [comment]
done

**Comment by ryanjbaxter** [comment]
I cherry picked this to the 1.0.x branch

**Pull request merged**
