### PR TITLE
fix - 1237

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Comment by wind57** [comment]
@ryanjbaxter one more PR regarding documentation. thank you

**Comment by ryanjbaxter** [comment]
Thanks this is great!

**Comment by ryanjbaxter** [comment]
I will merge it next week.  Its going to take some time to port everything to the main branch because of the documentation changes there and I am short on time right now

**Comment by wind57** [comment]
I completely get it, honestly! I bet the merge with broadcom has its burned too. I will patiently wait when this goes in and will tag you on the next one. take your time...

**Pull request merged**
