### PR TITLE
Set port name to <unset> in the case the name is null

### LINKED ISSUE #938: spring-cloud-kubernetes-discoveryserver: Null key for a Map not allowed in JSON for mssql service
**Describe the bug**
springcloud/spring-cloud-kubernetes-discoveryserver:2.1.1-SNAPSHOT (and 2.1.0 as well)
"http://127.0.0.1:35795/apps" gives 500 "EncodingException: JSON encoding error: Null key for a Map not allowed in JSON " when deploy `mssql` image
When i remove `mssql` service with next command it works fine.
```minikube kubectl -- delete service mssql2 ```

**Sample**
deployment scripts have been attached

minikube version: v1.24.0 commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b
Docker version 20.10.12, build e91ed57

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

**Exception:**
2021-12-16 06:46:28.109 ERROR 1 --- [undedElastic-16] a.w.r.e.AbstractErrorWebExceptionHandler : [c379292a-1]  500 Server Error for HTTP GET "/apps"

org.springframework.core.codec.EncodingException: JSON encoding error: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.ArrayList[0]->org.springframewok.cloud.kubernetes.discoveryserver.DiscoveryServerController$Service["serviceInstances"]->java.util.ArrayList[0]->org.springframework.cloud.kubernetes.commons.discovery.KubernetesServiceInstance["metadata"])
	at org.springframework.http.codec.json.AbstractJackson2Encoder.encodeValue(AbstractJackson2Encoder.java:229) ~[spring-web-5.3.13.jar:5.3.13]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler org.springframewok.cloud.kubernetes.discoveryserver.DiscoveryServerController#apps() [DispatcherHandler]
	*__checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP GET "/apps" [ExceptionHandlingWebHandler]

[mssql-deployment.zip](https://github.com/spring-cloud/spring-cloud-kubernetes/files/7725157/mssql-deployment.zip)

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #938

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
cc: @wind57

**Comment by weihubeats** [comment]
Hello, when will this version be released, I see that the latest maven repository is
image
But the code is still old
image

**Comment by ryanjbaxter** [comment]
We are currently planning doing a release next week that would contain this fix.  In the meantime you can use snapshot.

You can keep an eye on this release milestone
https://github.com/spring-cloud/spring-cloud-release/milestone/124

**Comment by weihubeats** [comment]
Okay, thank you very much!

**Pull request merged**
