### PR TITLE
Make Post Processor honor spring.cloud.kubernetes.enabled

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #420

### CODE REVIEW

**Comment by stefanocke** [comment]
@geoand , thank you. But shouldn't it be the other way around?

That is:
```
		final String enabledStr = environment.getProperty("spring.cloud.kubernetes.enabled", "true");
		if ("false".equals(enabledStr.toLowerCase())) {
			return;
		}
```

instead of 

```
		final String enabledStr = environment.getProperty("spring.cloud.kubernetes.enabled", "false");
		if ("true".equals(enabledStr.toLowerCase())) {
			return;
		}
```

The default for this property is true.
And the PostProcessor should return immediately,  if it is set to false.

**Comment by geoand** [comment]
@stefanocke you are absolutely right! It slipped through the cracks... I will push a fix

**Comment by spencergibb** [comment]
Already swapped in 599f96a7b3a85514033b08d18e1cf3f395c4a64a

**Comment by geoand** [comment]
Thanks @spencergibb !

**Pull request merged**
