### PR TITLE
fix wrong link-syntax in readme

### PR DESCRIPTION
**Pull request by rndmh3ro**

### CODE REVIEW

**Comment by spencergibb** [comment]
This change needed to be made is the asciidoc src folder. Once the readme is regenerated, this will be lost

**Comment by geoand** [comment]
Damn it... I always forget about that :(

**Comment by pukkaone** [comment]
While you're in there, would you also fix the incorrect link syntax here:
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/3409ad81a5aa21dc3468dc7f5f155304f50bf851/docs/src/main/asciidoc/property-source-config.adoc#L213

**Comment by ryanjbaxter** [comment]
@geoand can you port the changes to the asciidoc folder?

**Comment by geoand** [comment]
@ryanjbaxter Sure thing

**Comment by geoand** [comment]
@ryanjbaxter pushed  to master

**Comment by ryanjbaxter** [comment]
thanks!

**Comment by geoand** [comment]
yw!

**Pull request merged**
