### PR TITLE
README update for ConfigMap reload sample

### PR DESCRIPTION
**Pull request by anwarchk**
1. Fixed small typos
2. Removed notes about Spring Boot liveness and readiness check related
to Fabric8 since that issue has been resolved and is working as expected
3. Added sample configuration files for K8s RBAC set up required for the
example to work
4. Added section about how to setup RBAC config

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for the PR!

I am not sure that the ClusterServiceRole is actually the best way to go here (since it gives rights that might be too broad). @iocanel @salaboy WDYT?

**Comment by iocanel** [comment]
I agree we should go with plain old view role.

**Comment by anwarchk** [comment]
@geoand @iocanel We are still using the `view` role for the ServiceAccount. That is, we are binding the `config-reader` service account to the `view` ClusterRole. Is there a different example that you can please share that would bind to a less privileged role ? I would be happy to update the example config with that.

**Comment by anwarchk** [comment]
@ryanjbaxter ^^^

**Comment by geoand** [comment]
@anwarchk what I am concerned about is that it is a `ClusterRole`, meaning that it applies to all namespaces. If you could do the same but with a regular role, it would be enough I think

**Comment by anwarchk** [comment]
@geoand Updated the sample RBAC configs with a regular role

**Comment by geoand** [comment]
Thanks! Have you verified that this role works for your setup?

**Comment by anwarchk** [comment]
Yes, just did :-)

**Comment by geoand** [comment]
@ryanjbaxter would you like to take a look as well?

**Pull request merged**
