### PR TITLE
ensure config map names are unique based on absolute path, allowing s…

### PR DESCRIPTION
**Pull request by bruce-au**
…ame file names to be specified in different places

Fixes: https://github.com/spring-cloud/spring-cloud-kubernetes/issues/606

### CODE REVIEW

**Comment by bruce-au** [comment]
It doesn't seem like the integration test failure have anything to do with the changes. If they are, I'd appreciate if someone could help me understand the error, thanks!

**Comment by bruce-au** [comment]
@ryanjbaxter ping

**Review by ryanjbaxter — APPROVED** [review]
Can you submit this against the 1.1.x branch?  I can then merge it forward to master

**Comment by bruce-au** [comment]
Hey @ryanjbaxter I've updated the PR, thanks for looking at it

**Pull request merged**
