### PR TITLE
some polishing in KubernetesClientInfoContributor

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Comment by wind57** [comment]
these same changes were done in Fabric8InfoContributor, this this simply brings things on par with that one

**Comment by ryanjbaxter** [comment]
@wind57 let me know when this is ready to review

**Comment by ryanjbaxter** [comment]
@wind57 let me know when this is ready to review

**Comment by wind57** [comment]
@ryanjbaxter

**Pull request merged**
