### PR TITLE
#505 Ribbon should allow discovery across all namespaces

### PR DESCRIPTION
**Pull request by piomin**
It is related with issue https://github.com/spring-cloud/spring-cloud-kubernetes/issues/505.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Can you fix the conflicts?

**Comment by piomin** [comment]
Well, I gave up hope that anyone would take a look on it, and I add some other changes to my master branch not related with this issue :) Maybe, you could take a look on it if you really want to merge these changes (available in this first commit b3431ee), since they may be quite "controversial". They are allowing Ribbon to discover services by name also being available in the different namespace than the source service. And also when I was adding this change to your code, the build was broken due to failed integration tests in spring-cloud-kubernetes-config module. I have no idea why those tests were failed, since spring-cloud-kubernetes-config does not use spring-cloud-kubernetes-ribbon in any way.
If you still feel that this change is desirable, maybe I could create new PR from my branch dedicated for this change - not from the master. Otherwise you can just close this PR.
The another change, which was added in the menwhile is related to configmap versionning. I'm also not sure if you would like to merge such a change.

**Comment by piomin** [comment]
Well, I gave up hope that anyone would take a look on it, and I add some other changes to my master branch not related with this issue :) Maybe, you could take a look on it if you really want to merge these changes (available in this first commit b3431ee), since they may be quite "controversial". They are allowing Ribbon to discover services by name also being available in the different namespace than the source service. And also when I was adding this change to your code, the build was broken due to failed integration tests in spring-cloud-kubernetes-config module. I have no idea why those tests were failed, since spring-cloud-kubernetes-config does not use spring-cloud-kubernetes-ribbon in any way.
If you still feel that this change is desirable, maybe I could create new PR from my branch dedicated for this change - not from the master. Otherwise you can just close this PR.
The another change, which is visible here is related to configmap versioning. I'm also not sure if you really want to merge it?

**Comment by ryanjbaxter** [comment]
Sorry for the slow response.  I will close this for now and if the community decides it really wants this they can let us know.  Since Ribbon is being removed in master I dont know if it really makes sense.

**Pull request closed without merging**
