### PR TITLE
gson trimmers not used

### PR DESCRIPTION
**Pull request by wind57**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@yue9944882 is it fine we remove these?  I removed them from the auto config because we needed port information from the services and these were removing that information

**Comment by ryanjbaxter** [comment]
Let me know when this is ready

**Comment by wind57** [comment]
@yue9944882 still waiting on your input on this, please.

**Comment by yue9944882** [comment]
am fine removing this, the point of trimmers is for easing memory pressure from list-watching (every watch event will new an instance of kubernetes objects)

**Comment by wind57** [comment]
@ryanjbaxter finally this is ready to go...

**Pull request merged**
