### PR TITLE
Add spring.cloud.kubernetes.enabled as a metadata

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
This was already addressed here https://github.com/spring-cloud/spring-cloud-kubernetes/commit/98c7eb52d80f09962553ad8f5b0bf6f3689f8828

**Comment by spencergibb** [comment]
right, he's changing the unused class to a simple entry in metadata.

**Comment by eddumelendez** [comment]
Sorry my commit message is not clear. @spencegibb is right

**Comment by ryanjbaxter** [comment]
@eddumelendez sorry about that, can you submit this against the 1.1.x branch and we can merge it forward?

**Comment by eddumelendez** [comment]
@ryanjbaxter done!

**Pull request merged**
