### PR TITLE
Handle case where given entity to check readiness for is null/missing

### PR DESCRIPTION
**Pull request by jaredstehler**
resolves https://github.com/spring-cloud/spring-cloud-kubernetes/issues/804

### CODE REVIEW

**Comment by spencergibb** [comment]
can you add a test?

**Comment by steven-sheehy** [comment]
@jaredstehler Any update? Do you need any help on this? We're impacted by this as well so I can take this over if you don't have bandwidth to add those tests.

**Comment by jaredstehler** [comment]
let me take a crack at it this evening; i'll punt it over to you if I can't get something working.

**Comment by jaredstehler** [comment]
added a test

**Comment by jaredstehler** [comment]
@spencergibb this should be good to go now?

**Comment by steven-sheehy** [comment]
Is this still needed since fabric8 kubernetes-client 5.5.0 is now integrated with the fix to not throw IllegalArgumentException?

**Pull request closed without merging**
